---
# ------------------------------------#
# Namespace                           #
# ------------------------------------#
apiVersion: v1
kind: Namespace
metadata:
  name: ${K8S_NAMESPACE}
spec:
  finalizers:
    - kubernetes

---
# ------------------------------------#
# ConfigMap                           #
# ------------------------------------#
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${K8S_SERVICE_NAME}
  namespace: ${K8S_NAMESPACE}
data:
  SERVER: "${SERVER}"
  PORT: "${PORT}"
  PORT_SWAGGER: "${PORT_SWAGGER}"
  SWAGGER_HTTPS: "${SWAGGER_HTTPS}"
  LOGGER_LEVEL: ${LOGGER_LEVEL}
  NODE_ENV: ${NODE_ENV}
  FACE_ANALYTICS_SERVER: ${FACE_ANALYTICS_SERVER}
  FACE_ANALYTICS_PORT: "${FACE_ANALYTICS_PORT}"
  RESOURCES_PATH: ${RESOURCES_PATH}
  SFTP_HOST: ${SFTP_HOST}
  SFTP_PORT: "${SFTP_PORT}"
  SFTP_USER: ${SFTP_USER}
  DOMAIN: ${DOMAIN}
  ENV: "${ENV}"

---
# ------------------------------------#
# Secret                              #
# ------------------------------------#
apiVersion: v1
kind: Secret
metadata:
  name: ${K8S_SERVICE_NAME}-secret
  namespace: ${K8S_NAMESPACE}
type: Opaque
stringData:
  DATABASE_URL: "${DATABASE_URL}"
  TOKEN_KEY: "${TOKEN_KEY}"
  SFTP_PASSWORD: "${SFTP_PASSWORD}"
  GATEWAY_INTERNAL_SECRET: "${GATEWAY_INTERNAL_SECRET}"

---
# ------------------------------------#
# Deployment                          #
# ------------------------------------#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${K8S_SERVICE_NAME}
  namespace: ${K8S_NAMESPACE}
spec:
  replicas: ${K8S_MIN_REPLICAS}
  selector:
    matchLabels:
      app: ${K8S_SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${K8S_SERVICE_NAME}
    spec:
      containers:
      - name: ${K8S_SERVICE_NAME}
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: ${K8S_SERVICE_NAME}
          - secretRef:
              name: ${K8S_SERVICE_NAME}-secret
        resources:
          requests:
            cpu: ${K8S_RESOURCES_REQUESTS_CPU}
            memory: ${K8S_RESOURCES_REQUESTS_MEMORY}
          limits:
            cpu: ${K8S_RESOURCES_LIMITS_CPU}
            memory: ${K8S_RESOURCES_LIMITS_MEMORY}
        ports:
          - containerPort: ${PORT}
      imagePullSecrets:
        - name: dockerhub-regcred

---
# ------------------------------------#
# Service                             #
# ------------------------------------#
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${K8S_SERVICE_NAME}
  name: ${K8S_SERVICE_NAME}
  namespace: ${K8S_NAMESPACE}
spec:
  type: ClusterIP
  selector:
    app: ${K8S_SERVICE_NAME}
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: ${PORT}

---
# ------------------------------------#
# Ingress                             #
# ------------------------------------#
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ${K8S_SERVICE_NAME}
#  namespace: ${K8S_NAMESPACE}
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    cert-manager.io/cluster-issuer: "${CLUSTER_ISSUER}"
#    nginx.ingress.kubernetes.io/ssl-redirect: "true"
#    nginx.ingress.kubernetes.io/enable-cors: "true"
#    nginx.ingress.kubernetes.io/cors-allow-origin: "${CORS_ALLOW_ORIGIN}"
#    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-access-token,ngrok-skip-browser-warning"
#    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
#    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
#    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
#spec:
#  tls:
#    - hosts:
#      - ${DOMAIN}
#      secretName: ${K8S_SERVICE_NAME}-tls
#  rules:
#    - host: ${DOMAIN}
#      http:
#        paths:
#          - path: /
#            pathType: ImplementationSpecific
#            backend:
#              service:
#                name: ${K8S_SERVICE_NAME}
#                port:
#                  number: 443
